{% set name = "ranger-fm" %}
{% set version = "1.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bee308b636137b9135111fc795a57cdbb95257f2670101042ac3d7747dec32c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ranger
    - ranger.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ranger.github.io
  summary: Vim-like file manager
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
